name: Update Snake Animation

on:
    schedule:
        - cron: "0 */12 * * *" # Every 12 hours
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
          - name: Generates the Animation
            uses: Platane/snk@master
            with:
                github_user_name: brhaka
                svg_out_path: dist/github-contrib-snake.svg

          - name: Push .svg to the output branch
            uses: crazy-max/ghaction-github-pages@v2.5.0
            with:
                target_branch: output
                build_dir: dist
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
